package fr.gouv.vitam.tools.resip.frame;

import javax.swing.*;
import java.awt.*;

public class Test {
    public JCheckBox hachageCheckBox;
    public JCheckBox nomDeFichierCheckBox;
    public JCheckBox toutesMDFichiersCheckBox;
    public JCheckBox toutesMDPhysiquesCheckBox;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        hachageCheckBox = new JCheckBox();
        hachageCheckBox.setEnabled(false);
        hachageCheckBox.setSelected(true);
        hachageCheckBox.setText("Hachage");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(hachageCheckBox, gbc);
        toutesMDPhysiquesCheckBox = new JCheckBox();
        toutesMDPhysiquesCheckBox.setText("Toutes MD physiques");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(toutesMDPhysiquesCheckBox, gbc);
        toutesMDFichiersCheckBox = new JCheckBox();
        toutesMDFichiersCheckBox.setText("Toutes MD fichiers");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(toutesMDFichiersCheckBox, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Critères de recherche de doublons");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(label1, gbc);
        nomDeFichierCheckBox = new JCheckBox();
        nomDeFichierCheckBox.setText("Nom de fichier");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel2.add(nomDeFichierCheckBox, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel3, gbc);
    }
}
